---

- name: "Include setup tasks"
  include: tasks-initial.yml

- name: "Include detection tasks"
  include: tasks-teamcity-detect.yml

- name: "Include clean-up tasks"
  include: tasks-teamcity-clean.yml
  when:
    - teamcity_installed_version.stdout != teamcity_version
    - config_file.stat.exists == "true"

- name: "Include teamcity distribution tasks"
  include: tasks-teamcity-distribution.yml

- name: "Include config tasks"
  include: tasks-config.yml

- name: "Include teamcity service tasks"
  include: tasks-teamcity-service.yml

- name: "Look for MySQL"
  shell: "which mysql | grep mysql"
  register: which_mysql
  changed_when: false
  failed_when: false

- name: "Include mysql connector tasks"
  include: tasks-mysql-connector.yml
  when: "'mysql' in which_mysql.stdout"

- name: "Include mysql db tasks"
  include: tasks-mysql-db.yml
  when: "'mysql' in which_mysql.stdout"