---

- name: "Include setup tasks"
  include: tasks-initial.yml

- name: Ensure a valid version and build is configured.
  shell: "curl -I https://download.jetbrains.com/charisma/teamcity-{{ teamcity_version }}.{{ teamcity_version_build }}.zip"
  register: curl_teamcity_zip
  changed_when: false
  failed_when:
    - '"200 OK" not in curl_teamcity_zip.stdout'
    - '"302 Moved Temporarily" not in curl_teamcity_zip.stdout'

- name: "Include detection tasks"
  include: tasks-teamcity-detect.yml

- name: "Include clean-up tasks"
  include: tasks-teamcity-clean.yml
  when: config_file.stat.exists|bool == false

- name: "Include teamcity distribution tasks"
  include: tasks-teamcity-distribution.yml
  when: config_file.stat.exists|bool == false

- name: "Include config tasks"
  include: tasks-config.yml
  when: config_file.stat.exists|bool == false

- name: "Include teamcity service tasks"
  include: tasks-teamcity-service.yml
  when: config_file.stat.exists|bool == false
