---

- name: "TeamCity | Stop service"
  shell: "{{ teamcity_install_dir }}/bin/teamcity-server.sh stop"
  failed_when: false

- name: "Teamcity | Uninstall"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ teamcity_data_dir }}/TeamCity"
    - "{{ teamcity_data_dir }}/buildserver/lib/jdbc/"