---

- name: "Teamcity | Get distribution"
  get_url:
    url: "http://download.jetbrains.com/teamcity/TeamCity-{{ teamcity_version }}.tar.gz"
    dest: "/tmp/TeamCity-{{ teamcity_version }}.tar.gz"
    validate_certs: no
  tags:
    - teamcity

- name: "Teamcity | Ensure directory is writable"
  become: yes
  become_user: root
  file:
    path: "{{ teamcity_install_dir }}"
    state: directory
    mode: 0755
    recurse: true
  tags:
  - teamcity

- name: "Teamcity | Unpack distribution"
  become: yes
  become_user: root
  unarchive:
    src: "/tmp/TeamCity-{{ teamcity_version }}.tar.gz"
    dest: "{{ teamcity_install_dir }}"
    copy: "no"
  tags:
    - teamcity

- name: "Teamcity | Setup port in configuration"
  become: yes
  become_user: root
  replace:
    dest: "{{ teamcity_install_dir }}/TeamCity/conf/server.xml"
    regexp: "8111"
    replace: "{{ teamcity_port }}"
  tags:
    - teamcity