---

- name: "Config | Set environment"
  lineinfile:
    dest: /etc/environment
    regexp: 'TEAMCITY_DATA_PATH="{{ teamcity_data_dir }}/buildserver"'
    line: 'TEAMCITY_DATA_PATH="{{ teamcity_data_dir }}/buildserver"'

- name: "Config | Create user group"
  group:
    name: teamcity
    state: present

- name: "Config | Add users"
  user:
    name: teamcity
    shell: /bin/false
    state: present
    group: teamcity

- name: "Config | Create directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: teamcity
    group: teamcity
    mode: 0777
    recurse: true
  changed_when: false
  with_items:
    - "{{ teamcity_data_dir }}"
    - "/opt/teamcity"
    - "/opt/teamcity/TeamCity"

- name: "Config | Include OS-specific tasks for Debian/Ubuntu"
  include: tasks-config-debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Config | Include OS-specific tasks for RedHat/CentOS/REHL"
  include: tasks-config-redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'